version: '3'

services:
  db:
   image: mysql:8.0
   container_name: db
   volumes: 
      - dbdata:/var/lib/mysql
   environment:
      - MYSQL_DATABASE=wordpress
      -MYSQL_USER=
      -MYSQL_Password
     ports:
      - 1234:3306
     networks:
     - 
     
volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
    
    
    https://www.youtube.com/watch?v=Z44UJUXsOGA
    
